version: '3.6'
services:
  postgres:
    image: postgres:13
    ports:
      - '5832:5432' # expose pg on port 5832 to not collide with pg from elswhere
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - '6832:6379'
    volumes:
      - redis:/data

volumes:
  redis:
      driver: local
  db_data:
      driver: local

